# Album API requests

# { "title": "Landscape in Iceland", "description": "Picture by @danielsessler", "picture": "https://unsplash.com/photos/1IdbT_tio1Y/download?ixid=MnwxMjA3fDB8MXxhbGx8MTJ8fHx8fHwyfHwxNjQxNDk5MjMz&force=true&w=640" }

### Create a post - v1
POST http://localhost:5200/api/posts
Content-Type: application/json

{ "title": "Mount Fuji", "description": "Picture by Clay Banks / unsplash.com", "picture": "https://unsplash.com/photos/u27Rrbs9Dwc/download?ixid=MnwxMjA3fDB8MXxhbGx8fHx8fHx8fHwxNjM5MTQxMDA1&force=true&w=640" }

### Get all posts
GET http://localhost:5200/api/posts

### Get one post - v1
GET http://localhost:5200/api/posts/1

### Delete one post - v1
DELETE http://localhost:5200/api/posts/2



### Register a user - v2
POST http://localhost:5200/api/v2/auth/register
Content-Type: application/json

{ "login": "abc@def.com", "pwd": "abcde" }

### Login - v2
POST http://localhost:5200/api/v2/auth/login
Content-Type: application/json

{ "login": "abc@def.com", "pwd": "abcde" }

### Create a post - v2 - NO AUTH
POST http://localhost:5200/api/v2/posts
Content-Type: application/json

{ "title": "Landscape in Iceland", "description": "Picture by @danielsessler", "picture": "https://unsplash.com/photos/1IdbT_tio1Y/download?ixid=MnwxMjA3fDB8MXxhbGx8MTJ8fHx8fHwyfHwxNjQxNDk5MjMz&force=true&w=640" }

### Create a post - v2
POST http://localhost:5200/api/v2/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibG9naW4iOiJhYmNAZGVmLmNvbSIsImlhdCI6MTY0MTUwMDEzMX0.ZBaq5opQcu56QI_zfTNtfjPvkro6hrvxhcela10Ach8

{ "title": "Landscape in Iceland", "description": "Picture by @danielsessler", "picture": "https://unsplash.com/photos/1IdbT_tio1Y/download?ixid=MnwxMjA3fDB8MXxhbGx8MTJ8fHx8fHwyfHwxNjQxNDk5MjMz&force=true&w=640" }

### Create a post with tags - v2
POST http://localhost:5200/api/v2/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibG9naW4iOiJhYmNAZGVmLmNvbSIsImlhdCI6MTY0MTUwMDEzMX0.ZBaq5opQcu56QI_zfTNtfjPvkro6hrvxhcela10Ach8

{ "title": "Landmannalaugar - Iceland", "description": "In Landmannalaugar there are rhyolite mountains. Rhyolite is a felsic extrusive rock. (I have no idea what that is)", "picture": "https://i.imgur.com/WCzfMMt.jpeg", "tags": "iceland,mountains" }

### Like a post - v2
PUT http://localhost:5200/api/v2/posts/2/like
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibG9naW4iOiJhYmNAZGVmLmNvbSIsImlhdCI6MTY0MTUwMDEzMX0.ZBaq5opQcu56QI_zfTNtfjPvkro6hrvxhcela10Ach8

### Delete one post - v2
DELETE http://localhost:5200/api/v2/posts/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibG9naW4iOiJhYmNAZGVmLmNvbSIsImlhdCI6MTY0MTUwMDEzMX0.ZBaq5opQcu56QI_zfTNtfjPvkro6hrvxhcela10Ach8