# Album API requests

### Create a post - v1
POST http://localhost:5200/api/posts
Content-Type: application/json

{ "title": "Mount Fuji", "description": "Picture by Clay Banks / unsplash.com", "picture": "https://unsplash.com/photos/u27Rrbs9Dwc/download?ixid=MnwxMjA3fDB8MXxhbGx8fHx8fHx8fHwxNjM5MTQxMDA1&force=true&w=640" }

### Get one post - v1
GET http://localhost:5200/api/posts/100

### Delete one post - v1
DELETE http://localhost:5200/api/posts/2



### Register a user - v2
POST http://localhost:5200/api/v2/auth/register
Content-Type: application/json

{ "title": "Mount Fuji", "description": "Picture by Clay Banks / unsplash.com", "picture": "https://unsplash.com/photos/u27Rrbs9Dwc/download?ixid=MnwxMjA3fDB8MXxhbGx8fHx8fHx8fHwxNjM5MTQxMDA1&force=true&w=640" }

### Login - v2
POST http://localhost:5200/api/v2/auth/login
Content-Type: application/json

{ "title": "Mount Fuji", "description": "Picture by Clay Banks / unsplash.com", "picture": "https://unsplash.com/photos/u27Rrbs9Dwc/download?ixid=MnwxMjA3fDB8MXxhbGx8fHx8fHx8fHwxNjM5MTQxMDA1&force=true&w=640" }

### Create a post - v2
POST http://localhost:5200/api/v2/posts
Content-Type: application/json

{ "title": "Mount Fuji", "description": "Picture by Clay Banks / unsplash.com", "picture": "https://unsplash.com/photos/u27Rrbs9Dwc/download?ixid=MnwxMjA3fDB8MXxhbGx8fHx8fHx8fHwxNjM5MTQxMDA1&force=true&w=640" }

### Delete one post - v2
DELETE http://localhost:5200/api/posts/2